"""add terms_accepted_at to users

Revision ID: 0d196d12cd57
Revises: 29bd1b08a18d
Create Date: 2026-07-14 09:50:20.108301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d196d12cd57'
down_revision: Union[str, Sequence[str], None] = '29bd1b08a18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the user accepted the Terms & Conditions; NULL if not yet accepted'))
    # ### end Alembic commands ###

    # Backfill: already-approved users were manually vetted via the pending-approval
    # email flow, which itself contains a full terms-acceptance declaration - treat
    # that as implicit consent so they aren't forced to re-accept post-login.
    op.execute(
        "UPDATE users SET terms_accepted_at = created_at WHERE is_approved = true "
        "AND terms_accepted_at IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terms_accepted_at')
    # ### end Alembic commands ###
