"""Add payment and trial fields to users table

Revision ID: 3a9e14cfc7b3
Revises: 84a37684f0bb
Create Date: 2025-11-05 00:09:42.446568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9e14cfc7b3'
down_revision: Union[str, Sequence[str], None] = '84a37684f0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_paid', sa.Boolean(), server_default='false', nullable=False, comment='True if user has paid for current month'))
    op.add_column('users', sa.Column('free_trial_ends_at', sa.DateTime(timezone=True), nullable=True, comment='When the free trial expires (7 days from registration)'))
    op.create_index('idx_users_trial_status', 'users', ['free_trial_ends_at', 'has_paid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_trial_status', table_name='users')
    op.drop_column('users', 'free_trial_ends_at')
    op.drop_column('users', 'has_paid')
    # ### end Alembic commands ###
