"""widen provider support to 8 llm providers

Revision ID: 6c04c50307f1
Revises: f080d4881eb3
Create Date: 2026-07-15 09:27:54.278232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c04c50307f1'
down_revision: Union[str, Sequence[str], None] = 'f080d4881eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_api_keys', sa.Column('base_url', sa.Text(), nullable=True))
    op.add_column('user_api_keys', sa.Column('api_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

    # Same gap as ff39b099730f / f7c2d2e1cc98 / f080d4881eb3: autogenerate
    # doesn't detect CHECK constraint body changes when the constraint name
    # is unchanged, so these are added by hand.
    op.drop_constraint('ck_valid_provider', 'user_api_keys', type_='check')
    op.create_check_constraint(
        'ck_valid_provider',
        'user_api_keys',
        "provider IN ('openai', 'openai_responses', 'anthropic', 'google', "
        "'azure_openai', 'openai_generic', 'microsoft_foundry', 'ollama')",
    )
    op.drop_constraint(
        'chk_user_settings_valid_preferred_provider', 'user_settings', type_='check'
    )
    op.create_check_constraint(
        'chk_user_settings_valid_preferred_provider',
        'user_settings',
        "preferred_provider IS NULL OR preferred_provider IN ('openai', 'openai_responses', "
        "'anthropic', 'google', 'azure_openai', 'openai_generic', 'microsoft_foundry', 'ollama')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'chk_user_settings_valid_preferred_provider', 'user_settings', type_='check'
    )
    op.create_check_constraint(
        'chk_user_settings_valid_preferred_provider',
        'user_settings',
        "preferred_provider IS NULL OR preferred_provider IN ('openai', 'google', 'anthropic')",
    )
    op.drop_constraint('ck_valid_provider', 'user_api_keys', type_='check')
    op.create_check_constraint(
        'ck_valid_provider', 'user_api_keys', "provider IN ('openai', 'google', 'anthropic')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_api_keys', 'api_version')
    op.drop_column('user_api_keys', 'base_url')
    # ### end Alembic commands ###
