"""add macro columns to meals

Revision ID: a4bb3ba2cc9b
Revises: 386492be88b0
Create Date: 2026-03-17 13:48:32.095828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bb3ba2cc9b'
down_revision: Union[str, Sequence[str], None] = '386492be88b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('proteine', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('meals', sa.Column('carboidrati', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('meals', sa.Column('grassi', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'grassi')
    op.drop_column('meals', 'carboidrati')
    op.drop_column('meals', 'proteine')
    # ### end Alembic commands ###
