"""add_sex_field_to_user_settings

Revision ID: c26db5a9ab70
Revises: 8cbb7810e66b
Create Date: 2025-11-06 22:42:28.731343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26db5a9ab70'
down_revision: Union[str, Sequence[str], None] = '8cbb7810e66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('sex', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'sex')
    # ### end Alembic commands ###
