"""update database to baml data structure

Revision ID: fa70e8b10560
Revises: c2b6586ec79a
Create Date: 2025-11-06 22:13:09.099166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa70e8b10560'
down_revision: Union[str, Sequence[str], None] = 'c2b6586ec79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create new ENUM types
    unitamisura = postgresql.ENUM('KG', 'GR', 'L', 'ML', 'PZ', name='unitamisura')
    unitamisura.create(op.get_bind(), checkfirst=True)

    tipopasto = postgresql.ENUM('COLAZIONE', 'SPUNTINO_MATTINA', 'PRANZO', 'SPUNTINO_POMERIGGIO', 'CENA', name='tipopasto')
    tipopasto.create(op.get_bind(), checkfirst=True)

    giornosettimana = postgresql.ENUM('LUNEDI', 'MARTEDI', 'MERCOLEDI', 'GIOVEDI', 'VENERDI', 'SABATO', 'DOMENICA', name='giornosettimana')
    giornosettimana.create(op.get_bind(), checkfirst=True)

    # Alter columns to use new ENUM types
    op.alter_column('ingredients', 'unit',
               existing_type=sa.VARCHAR(),
               type_=unitamisura,
               existing_nullable=False,
               postgresql_using='unit::unitamisura')

    op.alter_column('meals', 'meal_type',
               existing_type=postgresql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'),
               type_=tipopasto,
               existing_nullable=False,
               postgresql_using='meal_type::text::tipopasto')

    op.alter_column('meals', 'day',
               existing_type=sa.INTEGER(),
               type_=giornosettimana,
               existing_nullable=False,
               postgresql_using='day::text::giornosettimana')

    op.alter_column('saved_recipes', 'meal_type',
               existing_type=postgresql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'),
               type_=tipopasto,
               existing_nullable=False,
               postgresql_using='meal_type::text::tipopasto')

    # Drop old ENUM type (if it exists)
    op.execute('DROP TYPE IF EXISTS mealtype CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_recipes', 'meal_type',
               existing_type=sa.Enum('COLAZIONE', 'SPUNTINO_MATTINA', 'PRANZO', 'SPUNTINO_POMERIGGIO', 'CENA', name='tipopasto'),
               type_=postgresql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'),
               existing_nullable=False)
    op.alter_column('meals', 'day',
               existing_type=sa.Enum('LUNEDI', 'MARTEDI', 'MERCOLEDI', 'GIOVEDI', 'VENERDI', 'SABATO', 'DOMENICA', name='giornosettimana'),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('meals', 'meal_type',
               existing_type=sa.Enum('COLAZIONE', 'SPUNTINO_MATTINA', 'PRANZO', 'SPUNTINO_POMERIGGIO', 'CENA', name='tipopasto'),
               type_=postgresql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'),
               existing_nullable=False)
    op.alter_column('ingredients', 'unit',
               existing_type=sa.Enum('KG', 'GR', 'L', 'ML', 'PZ', name='unitamisura'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
