# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class DietaSettimanale(BaseModel):
    nome: typing.Optional[str] = None
    dataInizio: typing.Optional[str] = Field(default=None, description='YYYY-MM-DD')
    dataFine: typing.Optional[str] = Field(default=None, description='YYYY-MM-DD')
    pasti: typing.List["Pasto"] = Field(description='Elenco piatto di tutti i pasti della settimana, ogni pasto include il giorno')

class HtmlStructure(BaseModel):
    h1: typing.Optional[str] = None
    h2: typing.List[str]
    p: typing.List[str]
    ul: typing.List[str]
    ol: typing.List[str]

class Ingrediente(BaseModel):
    nome: typing.Optional[str] = None
    quantita: typing.Optional[float] = None
    unita: typing.Optional[types.UnitaMisura] = None

class ListaSpesa(BaseModel):
    ingredienti: typing.List["Ingrediente"] = Field(description='Elenco aggregato di tutti gli ingredienti da acquistare per l\'intera settimana, con quantità sommate e unità di misura coerenti')

class Pasto(BaseModel):
    giorno: typing.Optional[types.GiornoSettimana] = None
    tipo: typing.Optional[types.TipoPasto] = None
    nome: typing.Optional[str] = None
    orario: typing.Optional[str] = Field(default=None, description='Orario del pasto')
    ingredienti: typing.Optional[str] = None
    calorie: typing.Optional[int] = None
    proteine: typing.Optional[int] = Field(default=None, description='Grammi di proteine')
    carboidrati: typing.Optional[int] = Field(default=None, description='Grammi di carboidrati')
    grassi: typing.Optional[int] = Field(default=None, description='Grammi di grassi')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
