# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def GeneraDietaSettimanale(self, dataInizio: str,giornoInizio: str,dataFine: str,giornoFine: str,peso: float,altezza: float,eta: typing.Optional[int],sesso: typing.Optional[str],obiettivo: str,altri_dati: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DietaSettimanale:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GeneraDietaSettimanale(dataInizio=dataInizio,giornoInizio=giornoInizio,dataFine=dataFine,giornoFine=giornoFine,peso=peso,altezza=altezza,eta=eta,sesso=sesso,obiettivo=obiettivo,altri_dati=altri_dati,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GeneraDietaSettimanale", args={
                "dataInizio": dataInizio,"giornoInizio": giornoInizio,"dataFine": dataFine,"giornoFine": giornoFine,"peso": peso,"altezza": altezza,"eta": eta,"sesso": sesso,"obiettivo": obiettivo,"altri_dati": altri_dati,
            })
            return typing.cast(types.DietaSettimanale, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GeneraListaSpesa(self, pasti: typing.List["types.Pasto"],
        baml_options: BamlCallOptions = {},
    ) -> types.ListaSpesa:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GeneraListaSpesa(pasti=pasti,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GeneraListaSpesa", args={
                "pasti": pasti,
            })
            return typing.cast(types.ListaSpesa, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GeneraRicetta(self, pasto: types.Pasto,
        baml_options: BamlCallOptions = {},
    ) -> types.HtmlStructure:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GeneraRicetta(pasto=pasto,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GeneraRicetta", args={
                "pasto": pasto,
            })
            return typing.cast(types.HtmlStructure, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ModificaDietaSettimanale(self, dietaCorrente: types.DietaSettimanale,richiestaModifica: str,peso: float,altezza: float,eta: typing.Optional[int],sesso: typing.Optional[str],obiettivo: str,oggiData: str,oggiGiorno: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DietaSettimanale:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ModificaDietaSettimanale(dietaCorrente=dietaCorrente,richiestaModifica=richiestaModifica,peso=peso,altezza=altezza,eta=eta,sesso=sesso,obiettivo=obiettivo,oggiData=oggiData,oggiGiorno=oggiGiorno,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ModificaDietaSettimanale", args={
                "dietaCorrente": dietaCorrente,"richiestaModifica": richiestaModifica,"peso": peso,"altezza": altezza,"eta": eta,"sesso": sesso,"obiettivo": obiettivo,"oggiData": oggiData,"oggiGiorno": oggiGiorno,
            })
            return typing.cast(types.DietaSettimanale, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GeneraDietaSettimanale(self, dataInizio: str,giornoInizio: str,dataFine: str,giornoFine: str,peso: float,altezza: float,eta: typing.Optional[int],sesso: typing.Optional[str],obiettivo: str,altri_dati: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.DietaSettimanale, types.DietaSettimanale]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GeneraDietaSettimanale", args={
            "dataInizio": dataInizio,"giornoInizio": giornoInizio,"dataFine": dataFine,"giornoFine": giornoFine,"peso": peso,"altezza": altezza,"eta": eta,"sesso": sesso,"obiettivo": obiettivo,"altri_dati": altri_dati,
        })
        return baml_py.BamlSyncStream[stream_types.DietaSettimanale, types.DietaSettimanale](
          __result__,
          lambda x: typing.cast(stream_types.DietaSettimanale, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DietaSettimanale, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GeneraListaSpesa(self, pasti: typing.List["types.Pasto"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ListaSpesa, types.ListaSpesa]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GeneraListaSpesa", args={
            "pasti": pasti,
        })
        return baml_py.BamlSyncStream[stream_types.ListaSpesa, types.ListaSpesa](
          __result__,
          lambda x: typing.cast(stream_types.ListaSpesa, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ListaSpesa, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GeneraRicetta(self, pasto: types.Pasto,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.HtmlStructure, types.HtmlStructure]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GeneraRicetta", args={
            "pasto": pasto,
        })
        return baml_py.BamlSyncStream[stream_types.HtmlStructure, types.HtmlStructure](
          __result__,
          lambda x: typing.cast(stream_types.HtmlStructure, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.HtmlStructure, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ModificaDietaSettimanale(self, dietaCorrente: types.DietaSettimanale,richiestaModifica: str,peso: float,altezza: float,eta: typing.Optional[int],sesso: typing.Optional[str],obiettivo: str,oggiData: str,oggiGiorno: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.DietaSettimanale, types.DietaSettimanale]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ModificaDietaSettimanale", args={
            "dietaCorrente": dietaCorrente,"richiestaModifica": richiestaModifica,"peso": peso,"altezza": altezza,"eta": eta,"sesso": sesso,"obiettivo": obiettivo,"oggiData": oggiData,"oggiGiorno": oggiGiorno,
        })
        return baml_py.BamlSyncStream[stream_types.DietaSettimanale, types.DietaSettimanale](
          __result__,
          lambda x: typing.cast(stream_types.DietaSettimanale, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DietaSettimanale, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GeneraDietaSettimanale(self, dataInizio: str,giornoInizio: str,dataFine: str,giornoFine: str,peso: float,altezza: float,eta: typing.Optional[int],sesso: typing.Optional[str],obiettivo: str,altri_dati: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneraDietaSettimanale", args={
            "dataInizio": dataInizio,"giornoInizio": giornoInizio,"dataFine": dataFine,"giornoFine": giornoFine,"peso": peso,"altezza": altezza,"eta": eta,"sesso": sesso,"obiettivo": obiettivo,"altri_dati": altri_dati,
        }, mode="request")
        return __result__
    def GeneraListaSpesa(self, pasti: typing.List["types.Pasto"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneraListaSpesa", args={
            "pasti": pasti,
        }, mode="request")
        return __result__
    def GeneraRicetta(self, pasto: types.Pasto,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneraRicetta", args={
            "pasto": pasto,
        }, mode="request")
        return __result__
    def ModificaDietaSettimanale(self, dietaCorrente: types.DietaSettimanale,richiestaModifica: str,peso: float,altezza: float,eta: typing.Optional[int],sesso: typing.Optional[str],obiettivo: str,oggiData: str,oggiGiorno: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ModificaDietaSettimanale", args={
            "dietaCorrente": dietaCorrente,"richiestaModifica": richiestaModifica,"peso": peso,"altezza": altezza,"eta": eta,"sesso": sesso,"obiettivo": obiettivo,"oggiData": oggiData,"oggiGiorno": oggiGiorno,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GeneraDietaSettimanale(self, dataInizio: str,giornoInizio: str,dataFine: str,giornoFine: str,peso: float,altezza: float,eta: typing.Optional[int],sesso: typing.Optional[str],obiettivo: str,altri_dati: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneraDietaSettimanale", args={
            "dataInizio": dataInizio,"giornoInizio": giornoInizio,"dataFine": dataFine,"giornoFine": giornoFine,"peso": peso,"altezza": altezza,"eta": eta,"sesso": sesso,"obiettivo": obiettivo,"altri_dati": altri_dati,
        }, mode="stream")
        return __result__
    def GeneraListaSpesa(self, pasti: typing.List["types.Pasto"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneraListaSpesa", args={
            "pasti": pasti,
        }, mode="stream")
        return __result__
    def GeneraRicetta(self, pasto: types.Pasto,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneraRicetta", args={
            "pasto": pasto,
        }, mode="stream")
        return __result__
    def ModificaDietaSettimanale(self, dietaCorrente: types.DietaSettimanale,richiestaModifica: str,peso: float,altezza: float,eta: typing.Optional[int],sesso: typing.Optional[str],obiettivo: str,oggiData: str,oggiGiorno: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ModificaDietaSettimanale", args={
            "dietaCorrente": dietaCorrente,"richiestaModifica": richiestaModifica,"peso": peso,"altezza": altezza,"eta": eta,"sesso": sesso,"obiettivo": obiettivo,"oggiData": oggiData,"oggiGiorno": oggiGiorno,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))