# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class GiornoSettimana(str, Enum):
    LUNEDI = "LUNEDI"
    MARTEDI = "MARTEDI"
    MERCOLEDI = "MERCOLEDI"
    GIOVEDI = "GIOVEDI"
    VENERDI = "VENERDI"
    SABATO = "SABATO"
    DOMENICA = "DOMENICA"

class TipoPasto(str, Enum):
    COLAZIONE = "COLAZIONE"
    SPUNTINO_MATTINA = "SPUNTINO_MATTINA"
    PRANZO = "PRANZO"
    SPUNTINO_POMERIGGIO = "SPUNTINO_POMERIGGIO"
    CENA = "CENA"

class UnitaMisura(str, Enum):
    KG = "KG"
    GR = "GR"
    L = "L"
    ML = "ML"
    PZ = "PZ"

# #########################################################################
# Generated classes (6)
# #########################################################################

class Dieta(BaseModel):
    giorno: GiornoSettimana
    pasti: typing.List["Pasto"]

class DietaSettimanale(BaseModel):
    nome: str
    dataInizio: str = Field(description='YYYY-MM-DD')
    dataFine: str = Field(description='YYYY-MM-DD')
    dieta: typing.List["Dieta"] = Field(description='Elenco dei giorni della settimana con i relativi pasti')

class HtmlStructure(BaseModel):
    h1: str
    h2: typing.List[str]
    p: typing.List[str]
    ul: typing.List[str]
    ol: typing.List[str]

class Ingrediente(BaseModel):
    nome: str
    quantita: float
    unita: UnitaMisura

class ListaSpesa(BaseModel):
    ingredienti: typing.List["Ingrediente"] = Field(description='Elenco aggregato di tutti gli ingredienti da acquistare per l\'intera settimana, con quantità sommate e unità di misura coerenti')

class Pasto(BaseModel):
    tipo: TipoPasto
    nome: str
    orario: str = Field(description='Orario del pasto')
    ingredienti: str
    calorie: int

# #########################################################################
# Generated type aliases (0)
# #########################################################################
