# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DietaSettimanale": types.DietaSettimanale,
    "stream_types.DietaSettimanale": stream_types.DietaSettimanale,

    "types.HtmlStructure": types.HtmlStructure,
    "stream_types.HtmlStructure": stream_types.HtmlStructure,

    "types.Ingrediente": types.Ingrediente,
    "stream_types.Ingrediente": stream_types.Ingrediente,

    "types.ListaSpesa": types.ListaSpesa,
    "stream_types.ListaSpesa": stream_types.ListaSpesa,

    "types.Pasto": types.Pasto,
    "stream_types.Pasto": stream_types.Pasto,


    "types.GiornoSettimana": types.GiornoSettimana,

    "types.TipoPasto": types.TipoPasto,

    "types.UnitaMisura": types.UnitaMisura,

}